app = "forecastflow-backend"  # ⚠️ Must be unique globally

primary_region = "ams"  # Use your nearest region: e.g. ams (Amsterdam), lhr (London), cdg (Paris)

[build]
  image = "python:3.11"

[env]
  PORT = "8000"

[experimental]
  auto_rollback = true

[[services]]
  internal_port = 8000
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "10s"
